listen=YES
#listen_ipv6=YES
local_enable=YES
write_enable=YES
local_umask=022

chroot_local_user=YES
allow_writeable_chroot=YES

pasv_enable=YES
pasv_min_port=21000
pasv_max_port=21010
anonymous_enable=NO

userlist_enable=NO
userlist_file=/etc/vsftpd.userlist
userlist_deny=NO

local_root=/var/www/html
chroot_list_enable=NO